### ISSUE TITLE
Connect to multiple databases in single rails application

### ISSUE THREAD

**Issue by dongtong** [dongtong/blog#34]
Sometimes, we need to connect to multiple databases in single rails application. The below is my practice in my application.

* Define database connection configuration in config/ext_databases, such as demo.yml

```
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  database: [the database your want to connect]
  username: [username]
  password: '[your db password]'
  host: [your db host]

development:
  <<: *default
  host: [your db host]

production:
  <<: *default
```

* Define connection constant in config/initializers, such as ext_database.rb

```
# define connection yaml file here
DEMO_DB = YAML.load_file(File.join(Rails.root, "config", "ext_databases", "demo.yml"))[Rails.env.to_s]
```

* Define ActiveRecord::Base subclass for db connection in  app/models/demo/base.rb

```
#encoding: utf-8
module Demo
  class Base < ActiveRecord::Base
    begin
      self.abstract_class = true
      establish_connection DEMO_DB
    rescue Exception => e
      Rails.logger.error(e.message)
      Rails.logger.error(e.backtrace.join("\n"))
    end
  end
end
```

* Define ORM, please remember that demo db's table name maybe do not follow rails rule. see the following example.

```
#encoding: utf-8
module Demo
  class Post < Gridx::Base
    self.table_name = "post"
  end
end
```

* Restart rails application and try to access Demo::Post records.
